### ISSUE TITLE
Setting credentials/access token via command line 

### ISSUE THREAD

**Issue by doergn** [SAP/quality-continuous-traceability-monitor#4]
...to avoid writting them into a file. (Jira and GitHub Credentials/access token)

**Comment by agarwal89** [comment]
Hi Team,
When we integrate CTM with our CICD pipeline, it fails with the error:

Error:
10:32:59 W c.s.d.c.f.r.d.DockerLogCallback - I1204 05:03:00.380571 7 config.go:113] Cloning sourcecode repository https://github.wdf.sap.corp// to /go/src/traceabilityEncabulator/Project-Management
10:33:00 W c.s.d.c.f.r.d.DockerLogCallback - Cloning into '/go/src/traceabilityEncabulator/Project-Management'...
10:33:00 W c.s.d.c.f.r.d.DockerLogCallback - fatal: protocol '"ssh' is not supported
10:33:00 W c.s.d.c.f.r.d.DockerLogCallback - E1204 05:03:00.387623 7 git.go:86] exit status 128
10:33:00 W c.s.d.c.f.r.d.DockerLogCallback - F1204 05:03:00.388015 7 git.go:44] Unable to clone https://github.wdf.sap.corp// to /go/src/traceabilityEncabulator/Project-Management
10:33:00 W c.s.d.c.f.r.d.DockerLogCallback - goroutine 1 [running]:


Please look into this and let us know how this can be fixed at the earliest as it it blocking our deployments.

Regards
Ankita
SAP email id: ankita.agarwal@sap.com

**Comment by MichaelSp** [comment]
Error location: https://github.com/SAP/quality-continuous-traceability-monitor/blob/395dbdc2b2d0838ce032bc70af0b6b4467a6af68/utils/git.go#L30-L46

**Comment by agarwal89** [comment]
Hello @MichaelSp  Thank you for the response. Please let me know who could help me fix this?

Regards
Ankita

**Comment by agarwal89** [comment]
Hello,
Any updates on the same please? Our CICD pipelines are blocked due to this issue.

**Comment by doergn** [comment]
This is not related to the inital issue here. Opening a new issue for your problem:
https://github.com/SAP/quality-continuous-traceability-monitor/issues/20
